# -*- coding: utf-8 -*-

"""
wordsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DefinitionsResponse(object):

    """Implementation of the 'DefinitionsResponse' model.

    This custom type contains response for definitions endpoint.

    Attributes:
        word (str): The word that is searched.
        definition (List[str]): The definitions of the searched word.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "word": 'word',
        "definition": 'definition'
    }

    def __init__(self,
                 word=None,
                 definition=None):
        """Constructor for the DefinitionsResponse class"""

        # Initialize members of the class
        self.word = word 
        self.definition = definition 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        word = dictionary.get("word") if dictionary.get("word") else None
        definition = dictionary.get("definition") if dictionary.get("definition") else None
        # Return an object of this model
        return cls(word,
                   definition)
