# -*- coding: utf-8 -*-

"""
wordsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ExamplesResponse(object):

    """Implementation of the 'ExamplesResponse' model.

    This custom type contains response for examples endpoint.

    Attributes:
        word (str): The word that is searched.
        examples (List[str]): The usage examples of the searched word.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "word": 'word',
        "examples": 'examples'
    }

    def __init__(self,
                 word=None,
                 examples=None):
        """Constructor for the ExamplesResponse class"""

        # Initialize members of the class
        self.word = word 
        self.examples = examples 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        word = dictionary.get("word") if dictionary.get("word") else None
        examples = dictionary.get("examples") if dictionary.get("examples") else None
        # Return an object of this model
        return cls(word,
                   examples)
