# -*- coding: utf-8 -*-

"""
wordsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SynonymsResponse(object):

    """Implementation of the 'SynonymsResponse' model.

    This custom type contains response for synonyms endpoint.

    Attributes:
        word (str): The word that is searched.
        synonyms (List[str]): The synonyms of the searched word.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "word": 'word',
        "synonyms": 'synonyms'
    }

    def __init__(self,
                 word=None,
                 synonyms=None):
        """Constructor for the SynonymsResponse class"""

        # Initialize members of the class
        self.word = word 
        self.synonyms = synonyms 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        word = dictionary.get("word") if dictionary.get("word") else None
        synonyms = dictionary.get("synonyms") if dictionary.get("synonyms") else None
        # Return an object of this model
        return cls(word,
                   synonyms)
